### PR TITLE
#ZM0sHy6Z Set up sequelize

### PR DESCRIPTION
**Pull request by ncutixavier**
### **What about this PR?**
This PR is about to configure the app to use Postgres database

### **Description of Task to be completed**
- Set up the migrations and models structure
- Dummy user table to test configuration

### **How should be manually tested?**
- Clone the repo
- checkout the branch `ch-set-up-sequelize-ZM0sHy6Z`
- Install all packages
- Create two Postgres databases one for test and the other for development and assign the values of the connection strings to DEV_DATABASE_URL and TEST_DATABASE_URL
- create **`.env`** file and insert those database's connection string
- Run this command `npm run migrate` to make migration or Run `npm run migrate:reset` to undo migration 
- Run this command `npm run seeding` to seed the database with dummy data
- You may check the data in your Postgres Db (Optionally)

### **Relevant pivots tracker**
[#ZM0sHy6Z](https://trello.com/c/ZM0sHy6Z/17-configure-the-app-to-use-postgres-database)

### CODE REVIEW

**Review by karigirwa — DISMISSED** [review]

**Review by Niyiragira — COMMENTED** [review]
You did some good job but you will need to redo a work which contains SWAGGER documentation and ESLINT configuration when it will be merged into develop

**Comment by Nkbtemmy** [comment]
there are same missed contents;
1. after cloning repo you just  do git checkout origin/branch-name
2.you might do migration before doing seeding
3. seeding command is npx sequelize-cli db:seed:all not the one you wrote

**Review by Nkbtemmy — DISMISSED** [review]

**Review by Niyiragira — DISMISSED** [review]

**Comment by Nkbtemmy** [comment]
mn you forget setting up in migration the user to be unique; when you continue doing migration people  repeated saved

**Comment by Nkbtemmy** [comment]
may be you can set email to be unique

**Comment by Niyiragira** [comment]
You will have to rebase develop in order to be on track

**Review by Nkbtemmy — DISMISSED** [review]

**Review by Niyiragira — DISMISSED** [review]

**Review by karigirwa — DISMISSED** [review]

**Comment by ceelogre** [comment]
As I've suggested before, add `.env.example` which shows keys without actual values, that way it's easier to create `.env` file based on it.

**Comment by ceelogre** [comment]
`seeding` command is not available.
Capture d’écran 2020-09-28 à 12 19 11

**Comment by ceelogre** [comment]
Can you find a way to automate the creation of the table?

Capture d’écran 2020-09-28 à 12 25 09

**Review by Niyiragira — APPROVED** [review]

**Review by Nkbtemmy — APPROVED** [review]

**Review by karigirwa — APPROVED** [review]

**Review by karigirwa — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
