### PR TITLE
#S7fu8nT3 Setup continuous integration and Heroku pipeline

### PR DESCRIPTION
**Pull request by karigirwa**
### **What does this PR do?**

 Setup Continuous Integration & Quality Assurance pipeline

### **Description of the task to be completed**

- Configured Testing environment with Mocha, Chai and Sinon to ensure that all functionalities are tested before deployment.
- Travis CI is configured as a continuous integration service used to build and test the app.
- Travis CI badge has been added to the repo
- Configure CodeClimate for code analysis and Maintainability checking.
- Configured Heroku Pipeline on Heroku

### **How should this be manually tested?**

- This can be tested by cloning this repo
- Checkout branch **origin/ch-continous-integration-S7fu8nT3**
- Run `npm install`
- Run `npm run test`
- Go to [Heroku](https://phantom-caba-ch-contino-e6c2ms.herokuapp.com/) to view deployment

###  **What are the relevant pivotal tracker stories?**

[#S7fu8nT3](https://trello.com/c/S7fu8nT3/18-setup-continuous-integration-quality-assurance-pipeline)

### CODE REVIEW

**Review by Niyiragira — DISMISSED** [review]

**Comment by Nkbtemmy** [comment]
All done well; congratulations

**Review by Nkbtemmy — APPROVED** [review]

**Review by Nkbtemmy — DISMISSED** [review]

**Review by ncutixavier — DISMISSED** [review]
Good Work.

**Review by Niyiragira — DISMISSED** [review]
Perfect !

**Review by ceelogre — CHANGES_REQUESTED** [review]
`.nyc_output` should not be tracked by git. You need to delete it.

**Review by Nkbtemmy — DISMISSED** [review]

**Review by ncutixavier — APPROVED** [review]

**Review by Nkbtemmy — APPROVED** [review]

**Review by Niyiragira — APPROVED** [review]

**Review by blaise82 — APPROVED** [review]

**Pull request merged**
